import '../../flexboxgrid.css'
import { v4 as uuidv4 } from 'uuid';

const dataProducts =[
    {
       id: 1,
       images : 'http://localhost:3000/imgs/product/product1.jpg' ,
       hotOffer: 'پیشنهاد ویژه',
       offerPer: '45%',
       stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
       title : 'کیف چرم بند دار',
       price : '۸۰۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
    } ,
    {
        id: 2,
        images : 'http://localhost:3000/imgs/product/product2.jpg' ,
        hotOffer : '' ,
        offerPer: '',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'لپ تاپ ایسوس 16 اینچ',
        price : '۲۳٫۰۰۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

    } ,
    {
        id: 3,
        images : 'http://localhost:3000/imgs/product/product3.jpg' ,
        hotOffer: '',
        offerPer: '',
        stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title: 'ژاکت مردانه ایزی دو',
        price : '۴۵۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

    } ,
    {
        id: 4,
        images : 'http://localhost:3000/imgs/product/product4.jpg' , 
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '25%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title: 'مجموعه 19 عددی دریل ساتا',
        price: '۲٫۵۶۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

    } ,
    {
        id: 5,
        images : 'http://localhost:3000/imgs/product/product5.jpg' , 
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '15%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title: 'نیم بوت مردانه مدل چرم مصنوعی',
        price: '۴۲۹٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

    } ,
    {
        id: 6,
        images : 'http://localhost:3000/imgs/product/product6.jpg' , 
        hotOffer: '',
        offerPer: '',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title: 'هدست مخصوص بازی جدل مدل GH-112',
        price: '۳۵۴٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

    } ,
    {
        id: 7,
        images : 'http://localhost:3000/imgs/product/product7.jpg' , 
        hotOffer: '',
        offerPer: '5%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
        price: '۲٫۵۸۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

    } ,
    {
        id: 8,
        images : 'http://localhost:3000/imgs/product/product8.jpg' , 
        hotOffer: '',
        offerPer: '',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title: 'پلیور یقه اسکی مردانه ایزی دو',
        price: '۴۵۸٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

    } ,
    {
        id: 9,
        images : 'http://localhost:3000/imgs/product/product9.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۸۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     } ,
     {
         id: 10,
         images : 'http://localhost:3000/imgs/product/product10.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۴٫۸۹۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     } ,
     {
         id: 11,
         images : 'http://localhost:3000/imgs/product/product11.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۸٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     } ,
     {
         id: 12,
         images : 'http://localhost:3000/imgs/product/product12.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۳۹۸٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     } ,
     {
         id: 13,
         images : 'http://localhost:3000/imgs/product/product13.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۳۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     } ,
     {
         id: 14,
         images : 'http://localhost:3000/imgs/product/product14.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۹۵۸٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     } ,
     {
         id: 15,
         images : 'http://localhost:3000/imgs/product/product15.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲۹٫۰۰۰٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     } ,
     {
         id: 16,
         images : 'http://localhost:3000/imgs/product/product2.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۸۵٫۰۰۰ تومان',
       moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',

     },
     {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 15,
          images : 'http://localhost:3000/imgs/product/product15.jpg' , 
          hotOffer: '',
          offerPer: '5%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
          price: '۲۹٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 16,
          images : 'http://localhost:3000/imgs/product/product2.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'پلیور یقه اسکی مردانه ایزی دو',
          price: '۴۸۵٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      },
      {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 15,
          images : 'http://localhost:3000/imgs/product/product15.jpg' , 
          hotOffer: '',
          offerPer: '5%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
          price: '۲۹٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 16,
          images : 'http://localhost:3000/imgs/product/product3.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'پلیور یقه اسکی مردانه ایزی دو',
          price: '۴۸۵٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      },
      {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 15,
          images : 'http://localhost:3000/imgs/product/product15.jpg' , 
          hotOffer: '',
          offerPer: '5%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
          price: '۲۹٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 16,
          images : 'http://localhost:3000/imgs/product/product2.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'پلیور یقه اسکی مردانه ایزی دو',
          price: '۴۸۵٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      },
      {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 15,
          images : 'http://localhost:3000/imgs/product/product15.jpg' , 
          hotOffer: '',
          offerPer: '5%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
          price: '۲۹٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 16,
          images : 'http://localhost:3000/imgs/product/product2.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'پلیور یقه اسکی مردانه ایزی دو',
          price: '۴۸۵٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      },
      {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 15,
          images : 'http://localhost:3000/imgs/product/product15.jpg' , 
          hotOffer: '',
          offerPer: '5%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
          price: '۲۹٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 16,
          images : 'http://localhost:3000/imgs/product/product2.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'پلیور یقه اسکی مردانه ایزی دو',
          price: '۴۸۵٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      },
      {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 15,
          images : 'http://localhost:3000/imgs/product/product15.jpg' , 
          hotOffer: '',
          offerPer: '5%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
          price: '۲۹٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 16,
          images : 'http://localhost:3000/imgs/product/product4.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'پلیور یقه اسکی مردانه ایزی دو',
          price: '۴۸۵٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      },
      {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 15,
          images : 'http://localhost:3000/imgs/product/product15.jpg' , 
          hotOffer: '',
          offerPer: '5%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
          price: '۲۹٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 16,
          images : 'http://localhost:3000/imgs/product/product3.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'پلیور یقه اسکی مردانه ایزی دو',
          price: '۴۸۵٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      },
      {
        id: 1,
        images : 'http://localhost:3000/imgs/product/product1.jpg' ,
        hotOffer: 'پیشنهاد ویژه',
        offerPer: '45%',
        stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
        title : 'کیف چرم بند دار',
        price : '۸۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
     } ,
     {
         id: 2,
         images : 'http://localhost:3000/imgs/product/product2.jpg' ,
         hotOffer : '' ,
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'لپ تاپ ایسوس 16 اینچ',
         price : '۲۳٫۰۰۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 3,
         images : 'http://localhost:3000/imgs/product/product3.jpg' ,
         hotOffer: '',
         offerPer: '',
         stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'ژاکت مردانه ایزی دو',
         price : '۴۵۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 4,
         images : 'http://localhost:3000/imgs/product/product4.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '25%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'مجموعه 19 عددی دریل ساتا',
         price: '۲٫۵۶۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 5,
         images : 'http://localhost:3000/imgs/product/product5.jpg' , 
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '15%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'نیم بوت مردانه مدل چرم مصنوعی',
         price: '۴۲۹٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 6,
         images : 'http://localhost:3000/imgs/product/product6.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'هدست مخصوص بازی جدل مدل GH-112',
         price: '۳۵۴٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 7,
         images : 'http://localhost:3000/imgs/product/product7.jpg' , 
         hotOffer: '',
         offerPer: '5%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'گوشی موبایل نوکیا مدل C21 TA-1352',
         price: '۲٫۵۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 8,
         images : 'http://localhost:3000/imgs/product/product8.jpg' , 
         hotOffer: '',
         offerPer: '',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title: 'پلیور یقه اسکی مردانه ایزی دو',
         price: '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
     } ,
     {
         id: 9,
         images : 'http://localhost:3000/imgs/product/product9.jpg' ,
         hotOffer: 'پیشنهاد ویژه',
         offerPer: '45%',
         stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
         title : 'کیف چرم بند دار',
         price : '۸۸۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 10,
          images : 'http://localhost:3000/imgs/product/product10.jpg' ,
          hotOffer : '' ,
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title : 'لپ تاپ ایسوس 16 اینچ',
          price : '۲۴٫۸۹۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 11,
          images : 'http://localhost:3000/imgs/product/product11.jpg' ,
          hotOffer: '',
          offerPer: '',
          stars : [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'ژاکت مردانه ایزی دو',
          price : '۴۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 12,
          images : 'http://localhost:3000/imgs/product/product12.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '25%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'مجموعه 19 عددی دریل ساتا',
          price: '۲٫۳۹۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 13,
          images : 'http://localhost:3000/imgs/product/product13.jpg' , 
          hotOffer: 'پیشنهاد ویژه',
          offerPer: '15%',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'نیم بوت مردانه مدل چرم مصنوعی',
          price: '۴۳۰٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      {
          id: 14,
          images : 'http://localhost:3000/imgs/product/product14.jpg' , 
          hotOffer: '',
          offerPer: '',
          stars: [<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>,<i class="fa-solid fa-star"></i>],
          title: 'هدست مخصوص بازی جدل مدل GH-112',
          price: '۹۵۸٫۰۰۰ تومان',
        moreDetail: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای',
 
      } ,
      
     
      
    
];

export default dataProducts ;